# Generated by Django 4.1.7 on 2023-02-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_alumni_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(db_column="enrollment_date", default="2022-11-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="profile_pic",
            field=models.URLField(db_column="profile_pic", default=1, max_length=256),
            preserve_default=False,
        ),
    ]
