# Generated by Django 4.1.7 on 2023-02-15 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course_alumni_app", "0002_student_enrollment_date_student_profile_pic"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="student",
            table="students",
        ),
    ]
