# Generated by Django 4.1.7 on 2023-02-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course_alumni_app", "0003_alter_student_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("Male", "M"), ("Female", "F")],
                db_column="gender",
                default="Male",
                max_length=6,
            ),
            preserve_default=False,
        ),
    ]
